// Test configuration for Playwright e2e tests
// Uses null catalogUrl so external paths work correctly
export default {
    catalogUrl: null,  // Tests use /search/external/... paths which work without a default catalog
    catalogTitle: "STAC Browser (Test)",
    catalogImage: null,
    allowExternalAccess: true,
    allowedDomains: [],
    detectLocaleFromBrowser: false,
    storeLocale: false,
    locale: "en",
    fallbackLocale: "en",
    supportedLocales: ["en"],
    apiCatalogPriority: null,
    useTileLayerAsFallback: false,
    displayGeoTiffByDefault: false,
    displayPreview: true,
    displayOverview: true,
    buildTileUrlTemplate: null,
    getMapSourceOptions: null,
    pathPrefix: "/",
    historyMode: "history",
    cardViewMode: "cards",
    cardViewSort: "asc",
    showKeywordsInItemCards: false,
    showKeywordsInCatalogCards: false,
    showThumbnailsAsAssets: false,
    searchResultsPerPage: null,
    itemsPerPage: null,
    collectionsPerPage: null,
    maxEntriesPerPage: 1000,
    defaultThumbnailSize: null,
    crossOriginMedia: null,
    requestHeaders: {},
    requestQueryParameters: {},
    socialSharing: [],
    preprocessSTAC: null,
    authConfig: null,
    crs: {},
    footerLinks: null,
    vizServer: null  // No viz server for tests - preview endpoints can be mocked
};
